version: '3'
# docker-compose -p "health" up -d
services:
  health:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - rede
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/projeto
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=projeto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rede
    volumes:
      - pg-data:/docker-entrypoint-initdb.d
  flyway:
    container_name: my-flyway
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=1234
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/projeto
      - FLYWAY_SCHEMAS=flyway
      - FLYWAY_GROUP=true
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - $PWD/sql_versions:/flyway/sql
    depends_on:
      - postgres
networks:
  rede:
    driver: bridge
volumes:
  pg-data:
